services:
  web:
    build: .
    command: python /app/manage.py runserver
    ports:
      - 8000:8000
    depends_on:
      - mvp_db
    volumes:
      - .:/app

  mvp_db:
    image: postgres:13
    volumes:
      - postgre_data:/var/lib/postgres/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgre_data: