# services:
#   web:
#     build: .
#     command: python /app/manage.py runserver
#     ports:
#       - 8000:8000
#     depends_on:
#       - mvp_db
#     volumes:
#       - .:/app

#   mvp_db:
#     image: postgres:13
#     volumes:
#       - postgre_data:/var/lib/postgres/data/
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"

#   react_app:
#     build:
#       context: ./react-app  # Path to your React app's Dockerfile
#       dockerfile: Dockerfile  # Name of your React app's Dockerfile
#     ports:
#       - 3000:3000
#     volumes:
#       - ./react-app:/app  # Path to your React app's source code


# volumes:
#   postgre_data:

version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    volumes:
      - ./react-app:/app

  postgres:
    image: postgres:13
    volumes:
      - postgre_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgre_data:
